name: hassfest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install hassfest
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade 'hassfest>=2024.12.0' || pip install --upgrade 'hassfest'

      - name: Run hassfest
        run: hassfest .
